### ISSUE TITLE
NameError: name 'log_file' is not defined

### ISSUE THREAD

**Issue by ddervosj** [MilindPurswani/Syborg#12]
Hello,

Receiving below error when running .py script :

python3 syborg.py test.com -w xxxwordlist.txt -c 50
Traceback (most recent call last):
  File "syborg.py", line 192, in <module>
    printVerbose("[*]["+getTime()+"] Logging to file %s" % log_file)
NameError: name 'log_file' is not defined

Any idea why is this happening?

Thanks

**Comment by MilindPurswani** [comment]
Hello, thanks for reporting this, I'll take a look into this and get back to you.

**Comment by MilindPurswani** [comment]
Hello, 
Can you post the exact command and output  that you are witnessing while invoking syborg?

**Comment by ddervosj** [comment]
python3 syborg.py test.com -w wordlist.txt -c 50

**Comment by MilindPurswani** [comment]
It seems my last commit last night, created this issue. https://github.com/MilindPurswani/Syborg/blob/76aef62b67d5c8d60dbf82c3f27fa01c7df8edc1/syborg.py

This should be fixed today.

**Comment by MilindPurswani** [comment]
Hi, this should be fixed now. 

Thanks again for bringing this in! Your help is appreciated :)

Thanks,

-Milind
