### ISSUE TITLE
Adding permutation to the wordlist can help generate results even more dynamic

### ISSUE THREAD

**Issue by Mrsharmax** [MilindPurswani/Syborg#5]
Tweak the script to make it resolve app-staging.example.com also along with all other words in wordlist in the place of staging.

**Comment by MilindPurswani** [comment]
That's a great idea! I believe there are already other tools which are working in a similar manner such as dnsgen and altdns. On a second thought, I am wondering if we should add this to Syborg. Maybe we can create a `CreativeUse.md` file and incorporate those syntaxes?

**Comment by MilindPurswani** [comment]
Maybe we can use these tools to generate a wordlist and then use syborg's Dead-end avoidance algorithm with DFS/BFS to add them to the chain of domains to query.

**Comment by MilindPurswani** [comment]
@itsgopsss 

Checkout the new [`Creative Usage Guidelines`](https://github.com/MilindPurswani/Syborg/blob/master/Syborg%20Creative%20Usage%20Guidelines.md). I hope you achieve more positive results with this 👍
